[build]
  functions = "functions" # Directory where Netlify should look for your functions

[[plugins]]
  package = "netlify-plugin-function-builder"

[[plugins]]
  package = "netlify-plugin-functions-install"